version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ./BlazorBaseApi/Dockerfile
    ports:
      - "7031:7031"

  front:
    build:
      context: .
      dockerfile: ./BlazorBase/Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - api